### ISSUE TITLE
Unicode Error In downloader.py

### ISSUE THREAD

**Issue by gerryof** [virtualarchitectures/CSO_Ireland_JSONStat4Py#1]
When using the jsonstat package I ran into an error that may be a bug. I was using this api url "https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/CJA07/JSON-stat/2.0/en". 

`url = 'https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/CJA07/JSON-stat/2.0/en'

filename = "crimeapi.json"

cache = jsonstat.download(url, filename)`

It returned  this error "UnicodeEncodeError: 'charmap' codec can't encode character '\x81' in position 9165: character maps to <undefined>".

By changing line 58 in the downloader.py script from  html = response.text to html = response.text.encode('cp850','replace').decode('cp850') I managed to get around the issue.

**Comment by virtualarchitectures** [comment]
Hi @gerryof thank you for the notification. I had a very quick check but wasn't able to identify the specific line item. The downloader.py script is part of [jsonstat.py](https://github.com/26fe/jsonstat.py) package dependency so any changes required to that package would need to be raised there. That said the issue sounds like it could be a problem with a specific character in the CSO api response. If you can identify the character that is causing the problem I recommend either contacting the CSO to have them correct the data up stream, otherwise you can raise the issue of handling character encodings by jsonstat.py directly on the project repository: https://github.com/26fe/jsonstat.py). As the problem can't be resolved within the jupyter notebook in this repository I'm closing the issue.
